format_version: 10
pipelines:
  master-ami:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/Prajaika/master-ami.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:YV42gYq2yWYCgg9bBS751w==:0J4Y60lLT3HsxDdkAdXTMky20Zle8D6iW9YBArhOCqk=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init" ], run_if: passed}
                - exec: {command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed}

